name: Angular Deploy to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.19' # Change this to your preferred Node.js version

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Install dependencies
        run: npm ci

      - name: Linting
        run: ng lint

      # - name: Unit tests
      #   run: ng test

      - name: Build Angular App for Production
        run: ng build --configuration=production


      - name: Deploy to Firebase Hosting
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting --project coincryptohub
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}


